import { Poppins } from "next/font/google";
import "./globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};
const font = Poppins({ subsets: ["latin"], weight: ["400", "700"] });
export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={font.className}>
				<h1 style={{ padding: 10 }}>ROLÊ-APP</h1>
				{children}
			</body>
		</html>
	);
}
